name: fake_store_package
description: "Paquete con el consumo del Fake Store API en Dart"
version: 1.0.0
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  http: ^1.2.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: